"""``lfv init``: scaffold a starter spec and optional project config.

The starter is intentionally small but non-trivial — a two-variable counter
with an increment action, a bound invariant, and a reachability check — so
the first ``lfv check`` passes and shows off the IR shape.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .config import DEFAULT_BOUND, DEFAULT_SEARCH

STARTER_SPEC: dict[str, Any] = {
    "name": "Starter",
    "description": (
        "Starter spec generated by lfv init. A counter that increments "
        "until it hits its domain ceiling. All checks pass."
    ),
    "variables": [
        {
            "name": "n",
            "domain": [0, 1, 2, 3, 4],
            "comment": "counter value",
        },
        {
            "name": "done",
            "domain": [False, True],
            "comment": "true once the counter saturates",
        },
    ],
    "init": {
        "kind": "binop",
        "op": "and",
        "left": {
            "kind": "binop",
            "op": "eq",
            "left": {"kind": "var", "name": "n"},
            "right": {"kind": "lit", "value": 0},
        },
        "right": {
            "kind": "binop",
            "op": "eq",
            "left": {"kind": "var", "name": "done"},
            "right": {"kind": "lit", "value": False},
        },
    },
    "actions": [
        {
            "name": "Increment",
            "guard": {
                "kind": "binop",
                "op": "and",
                "left": {
                    "kind": "unary",
                    "op": "not",
                    "operand": {"kind": "var", "name": "done"},
                },
                "right": {
                    "kind": "binop",
                    "op": "lt",
                    "left": {"kind": "var", "name": "n"},
                    "right": {"kind": "lit", "value": 4},
                },
            },
            "assignments": [
                {
                    "target": "n",
                    "expr": {
                        "kind": "binop",
                        "op": "add",
                        "left": {"kind": "var", "name": "n"},
                        "right": {"kind": "lit", "value": 1},
                    },
                }
            ],
            "comment": "n := n + 1 while not done and n < 4",
        },
        {
            "name": "Finish",
            "guard": {
                "kind": "binop",
                "op": "eq",
                "left": {"kind": "var", "name": "n"},
                "right": {"kind": "lit", "value": 4},
            },
            "assignments": [
                {
                    "target": "done",
                    "expr": {"kind": "lit", "value": True},
                }
            ],
            "comment": "mark done at the ceiling",
        },
    ],
    "invariants": [
        {
            "name": "n_in_range",
            "kind": "safety",
            "expr": {
                "kind": "binop",
                "op": "ge",
                "left": {"kind": "var", "name": "n"},
                "right": {"kind": "lit", "value": 0},
            },
        }
    ],
    "checks": [
        {
            "name": "can_finish",
            "kind": "liveness",
            "expr": {"kind": "var", "name": "done"},
            "comment": "done becomes true within the bound",
        }
    ],
}

STARTER_CONFIG: dict[str, Any] = {
    "bound": DEFAULT_BOUND,
    "search": DEFAULT_SEARCH,
}

SPEC_FILENAME = "spec.json"
CONFIG_FILENAME = ".lfv.json"


def write_starter(
    directory: str | Path,
    *,
    spec_name: str = SPEC_FILENAME,
    config_name: str | None = CONFIG_FILENAME,
    force: bool = False,
) -> list[Path]:
    """Write starter files into ``directory``. Returns the paths written.

    Raises :class:`FileExistsError` if a target already exists and
    ``force`` is false.
    """
    base = Path(directory)
    base.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    spec_path = base / spec_name
    if spec_path.exists() and not force:
        raise FileExistsError(f"{spec_path} already exists (use --force to overwrite)")
    spec_path.write_text(
        json.dumps(STARTER_SPEC, indent=2) + "\n", encoding="utf-8"
    )
    written.append(spec_path)

    if config_name is not None:
        config_path = base / config_name
        if config_path.exists() and not force:
            raise FileExistsError(
                f"{config_path} already exists (use --force to overwrite)"
            )
        config_path.write_text(
            json.dumps(STARTER_CONFIG, indent=2) + "\n", encoding="utf-8"
        )
        written.append(config_path)

    return written


__all__ = [
    "STARTER_SPEC",
    "STARTER_CONFIG",
    "SPEC_FILENAME",
    "CONFIG_FILENAME",
    "write_starter",
]
